### ISSUE TITLE
Scripts

### ISSUE THREAD

**Issue by vlbee** [sbinlondon/FAC-Week5-MSJK#35]
https://github.com/sbinlondon/FAC-Week5-MSJK/blob/master/package.json#L6-L8

Nice that you set up a code coverage testing script 👏

I also  recommend setting up a start script for running your site locally. This ensures you create a consistent dev environment across all developers on the team. 

```
  "scripts": {
    "start": "nodemon src/server.js",
  },
```

Fyi you can also use nodemon on your test script :)

**Comment by sbinlondon** [comment]
Thanks! We've added npm start :)
