### ISSUE TITLE
Clarity in parsing

### ISSUE THREAD

**Issue by tdoran** [sbinlondon/FAC-Week5-MSJK#44]
Nice structuring of data in your parsing functions!

Since you're taking one array (data.response.results) and making a new array (Guardian), it might be worth using the .map method (for clarity and brevity)
https://github.com/sbinlondon/FAC-Week5-MSJK/blob/c983084a679683ea5bf36d00cf20f3a4c8f5ebfb/src/parser.js#L6-L13

**Spoiler below**!! Example of how to do with .map : 

```js
let articles = data.response.results.map(el => {
  return {
    heading : el.fields.headline,
    date: el.webPublicationDate,
    img_url: el.fields.thumbnail,
    link_url: el.fields.shortUrl
  }
})
let result = {Guardian : articles} 
```

**Comment by arrested-developer** [comment]
😻 this is good looking code! Thanks
