### ISSUE TITLE
Creating discreet 404 page

### ISSUE THREAD

**Issue by tdoran** [sbinlondon/FAC-Week5-MSJK#50]
Firstly: great 404 page!😂

I think I was chatting with you when you encountered a problem with serving your 404.
I think it would make for clearer code if you had an independent html file you served instead of a string of all the html elements (also I wonder will that string run into issues with eslint if you had it formatting on save?).

https://github.com/sbinlondon/FAC-Week5-MSJK/blob/c983084a679683ea5bf36d00cf20f3a4c8f5ebfb/src/handlers.js#L7-L30

Let me know if you're still encountering issues serving your 404 html and we can take another look!

**Comment by sbinlondon** [comment]
We do have a 404.html file, it was that we couldn't figure out how to serve it. We'll definitely look into that today, because I agree that having a huge html string is a bit 👎

**Comment by tdoran** [comment]
Oops - missed that! But yes, hopefully you can serve the 404.html!

**Comment by arrested-developer** [comment]
I think the issue was actually to do with the handler (the missing `else` block), so we should be able to serve up the HTML file using fs without issue now
